export enum UserType {
    BUSINESS = "BUSINESS",
    RIDER = "RIDER",
    CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
    GAS_STATION = "GAS_STATION",
    INDIVIDUAL = "INDIVIDUAL",
    MERCHANT = 'MERCHANT'
}